### ISSUE TITLE
repeatedly making index of genome for each lib

### ISSUE THREAD

**Issue by pokhrelsuresh** [atulkakrana/helper.github#3]
Hi Atul,

I used your preprocessing script, which is really good. However, it does index for each library so making indexing repetitive. Can you check on this?

Thanks,
Suresh

**Comment by atulkakrana** [comment]
Hi Suresh,

Thanks for reporting this. I will take a look and fix it soon.

Atul

**Comment by pokhrelsuresh** [comment]
Hi Atul, 
Thank you for your response. It also doesn't produce final two graphs after trimming and chopping although the @mapperStep set to 1.

Suresh

**Comment by atulkakrana** [comment]
Great. I like people who report bugs. I will fix it.

Atul

**Comment by atulkakrana** [comment]
Hi Suresh,

The bug is fixed now. The updated script is faster too. I will close the issue for now. If you come across any other bug than please report it here.

Atul
